site_name: How to connect a Zune device to the Zune software
site_url: https://josh-wong.github.io/zune-software-setup/
site_description: A tutorial that describes how to connect a Microsoft Zune device to the Zune software.

# Add repo details in the top right-hand corner
repo_name: josh-wong/zune-software-setup
repo_url: https://github.com/josh-wong/zune-software-setup/
edit_uri: blob/main/docs

plugins:
  - search
  # Enables TechDocs support in Backstage. However, many plugins need to be disabled for TechDocs to work properly.
  #- techdocs-core
  # Show the last updated date
  - git-revision-date-localized:
      type: date
  # Enable videos to be embedded
  - mkdocs-video:
      css_style:
        width: "100%"
        height: "300px"
  - git-committers:
      repository: josh-wong/zune-software-setup
      branch: main

theme:
  name: mkdocs
  # Add favicon to browser tab
  favicon: assets/images/favicon.png
  # Add logo to docs pages
  logo: assets/images/mkdocs_zune_logo.png

