site_name: 🎵How to connect a Zune device to the Zune software
theme:
  name: material

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Installation:
    - Installing the Zune software: '02_installing-the-zune-software.md'
    - Connecting to the Zune software: '03_connecting-with-the-zune-software.md'
    - Adding apps and games (Zune HD only): '04_adding-apps-and-games.md'
  - Conclusion: '05_conclusion.md'
  - References: '06_references.md'
  - Contributions: '07_contributions.md'
  - Donations: '08_donations.md'
  - ⬅️return to josh-wong: 'https://josh-wong.github.io/'