site_name: How to connect a Zune device to the Zune software
site_url: https://josh-wong.github.io/zune-software-setup/

# adds repo details in the top right-hand corner; removing since it's 
# to have in a multidocs site
repo_name: josh-wong/zune-software-setup
repo_url: https://github.com/josh-wong/zune-software-setup
# removes the edit page button since there's a conflict with having the edit 
# page button on both single docs sites and this multidocs site; doesn't seem 
# to be a way to remove it from one site and keep it on the other
edit_uri: ""

plugins:
  - search

theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/mkdocs_zune_logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: blue
      accent: blue
  features:
    - search.suggest

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Installing the Zune software: '02_installing-the-zune-software.md'
  - Connecting to the Zune software: '03_connecting-with-the-zune-software.md'
  - Adding apps and games (Zune HD only): '04_adding-apps-and-games.md'
  - Conclusion: '05_conclusion.md'
  - References: '06_references.md'
  - Contributions: '07_contributions.md'
  - Donations: '08_donations.md'